# [[plugins]]
# repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'suzuki-shunsuke/denite-directory_mru-source'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
